# Generated by Django 4.1.2 on 2023-08-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SapmleTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_data", models.CharField(max_length=100)),
            ],
            options={"db_table": "sample_table",},
        ),
    ]
